# Generated by Django 5.2.7 on 2025-12-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_internship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='age',
        ),
        migrations.RemoveField(
            model_name='application',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='application',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='application',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='application',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='application',
            name='internship_location',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='application',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='application',
            name='role',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_location',
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_reply',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='internship_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='internship_max_experience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='internship_max_stipend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='internship_min_experience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='internship_min_qualification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='internship_min_stipend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='internship_required_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='internship_required_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='internship_sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='internships_benifits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='required_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='selection_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='total_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user_district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user_experience',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user_specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user_stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
