# Generated by Django 5.2.7 on 2025-12-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_internship', '0002_remove_application_age_remove_application_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='internships_benifits',
            new_name='internships_benefits',
        ),
        migrations.AlterField(
            model_name='application',
            name='selection_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
