# Generated by Django 5.2.7 on 2025-12-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_internship', '0003_rename_internships_benifits_application_internships_benefits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='internships_benefits',
            new_name='internship_benefits',
        ),
    ]
