# Generated by Django 5.2.7 on 2026-01-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_internship', '0004_rename_internships_benefits_application_internship_benefits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='internship_max_stipend',
            new_name='is_exp_in_range',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='internship_max_experience',
            new_name='max_exp_gap',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='internship_min_experience',
            new_name='min_exp_gap',
        ),
        migrations.RemoveField(
            model_name='application',
            name='company',
        ),
        migrations.RemoveField(
            model_name='application',
            name='date_of_reply',
        ),
        migrations.RemoveField(
            model_name='application',
            name='internship_benefits',
        ),
        migrations.RemoveField(
            model_name='application',
            name='internship_min_qualification',
        ),
        migrations.RemoveField(
            model_name='application',
            name='internship_min_stipend',
        ),
        migrations.RemoveField(
            model_name='application',
            name='internship_required_age',
        ),
        migrations.RemoveField(
            model_name='application',
            name='required_gender',
        ),
        migrations.RemoveField(
            model_name='application',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_age',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_district',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_gender',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_qualification',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_specialization',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_state',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_stream',
        ),
    ]
