# Generated by Django 5.2.7 on 2026-01-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_internship', '0005_rename_internship_max_stipend_application_is_exp_in_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='csv_ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
