# Generated by Django 5.2.7 on 2026-01-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_internship', '0006_application_csv_ref_id'),
    ]

    operations = [
    ]
