# Generated by Django 5.2.7 on 2026-01-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_internship', '0007_auto_20260105_0038'),
    ]

    operations = [
    ]
